### ISSUE TITLE
(node wrapper) signin errors treated differently than others

### ISSUE THREAD

**Issue by forana** [catalyzeio/catalyze-js-sdk#2]
Signin errors only include the contents of the `errors` property, while others include the full JSON response.

**Comment by cherukumilli** [comment]
I am using the catalyze.io's node library.
I was wondering if this issue has been fixed or not.

**Comment by forana** [comment]
@cherukumilli it appears that this has been fixed by the recent update we (Catalyze) performed on our backend - I am no longer able to reproduce it. Are you currently encountering this?

**Comment by cherukumilli** [comment]
@forana 

I am not encountering it but routes.js in catalyze-backend-node-example on github is still referencing the issue. Please check line# 34 in routes.js.

https://github.com/catalyzeio/catalyze-backend-node-example/blob/master/src/routes.js

**Comment by forana** [comment]
Actually, managed to reproduce this though that - the actual issue is in the `sessionFromToken` functionality. Fix coming up shortly.
