### ISSUE TITLE
sessionFromToken method on catalyze is returning the sessionUser

### ISSUE THREAD

**Issue by orthodoc** [catalyzeio/catalyze-js-sdk#5]
I am using the angular version to return the session object like so:

```js
catalyze.signIn(username, password, function(sessionObj) {
  console.log(sessionObj);
  $rootScope.usersId = sessionObj.usersId;
  $rootscope.sessionToken = sessionObj.token;
)};
```

Elsewhere, specifically in a logout function when I attempt to retrieve the session object via the usersId and sessionToken, like so:

```js
var usersId = $scope.usersId;
var sessionToken = $scope.sessionToken;
catalyze.sessionFromToken(usersId, sessionToken, function(session) {
  console.log(session);
)};
```
sessionObj !== session
In the console it appears to be the sessionUser
I am trying to use the signOut method which is available on the session object as per the sdk docs. However, herein the signOut method returns am unknown function error as the recreated session object is a sessionUser.

**Comment by orthodoc** [comment]
It appears to me from inspecting the core.js file that if a session object already exists, like in my use case then an error is raised and the sessionUser is returned instead.

lines 47 - 71
```js
// Create a session object from a usersId and token
    self.sessionFromToken = function(usersId, token, success, error) {
        var session = new Session(usersId, token);
        if (session.sessionUser) {
            if (error) {
                success(session);
            } else {
                success(null, session);
            }
        } else {
            session.retrieveUser(session.usersId, function(value, second) {
                if (error != null) { // non-node
                    session.sessionUser = value;
                    success(session);
                } else { // node
                    if (value) {
                        success(value);
                    } else {
                        session.sessionUser = second;
                        success(false, session);
                    }
                }
            }, error);
        }
    };
```

**Comment by forana** [comment]
Hi @orthodoc, thanks for the issue! I believe your trouble might be happening because you are not passing a callback for `error` (which is expected for jQuery and angular), causing those lines to behave erroneously. Could you try adding error callbacks and see if your issue still occurs?

More info on those callbacks: https://github.com/catalyzeio/catalyze-js-sdk/blob/master/docs.md

**Comment by forana** [comment]
Closing this as I haven't heard back - feel free to re-open this if it's still an issue.
